name: Python application

on:
    push:
        branches: [main]
    
jobs:
    build:

        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2
        - name: Set up Python 3.8
          uses: actions/setup-python@v2
          with:
            python-version: 3.8
        - name: Install dependencies
          run: |
            python -m venv venv
            source venv/bin/activate
            make install
        - name: Run tests
          run: |
            make run