name: Python application

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2

        - name: Set up Python 3.8
          uses: actions/setup-python@v2
          with:
            python-version: 3.8

        - name: Install dependencies
          run: |
            python -m venv venv
            source venv/bin/activate
            pip install --upgrade pip
            make install

        - name: Run app on port 3000
          run: |
            source venv/bin/activate
            make run &
            sleep 5 # wait for the server to start

        - name: Check if server is running
          run: |
            curl --fail http://localhost:3000 || exit 1
