name: Python application

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Set up Python 3.8
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    # Create virtual environment and install dependencies
    - name: Install dependencies
      run: |
        make venv
        . venv/bin/activate && make install

    # Run Flask app on port 3000
    - name: Run app on port 3000
      run: |
        . venv/bin/activate && make run &
        sleep 10  # Allow time for server to start

    # Check if app is running
    - name: Test server
      run: curl --fail http://localhost:3000 || exit 1
